// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items(title, price, user_id, created, updated)
VALUES ($1, $2, $3, $4, $5)
  RETURNING id, title, price, user_id, created, updated
`

type CreateItemParams struct {
	Title   string        `json:"title"`
	Price   int32         `json:"price"`
	UserID  sql.NullInt32 `json:"user_id"`
	Created sql.NullTime  `json:"created"`
	Updated sql.NullTime  `json:"updated"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.queryRow(ctx, q.createItemStmt, createItem,
		arg.Title,
		arg.Price,
		arg.UserID,
		arg.Created,
		arg.Updated,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Price,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password, created, updated)
VALUES ($1, $2, $3, $4, $5)
  RETURNING id, username, email, created, updated
`

type CreateUserParams struct {
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Password string       `json:"password"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

type CreateUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Created,
		arg.Updated,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, created, updated
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, title, price, user_id, created, updated
FROM items
ORDER BY id
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.query(ctx, q.listItemsStmt, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Price,
			&i.UserID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created, updated
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
